"""add note_chunks table

Revision ID: 10fe2495f036
Revises: e4332cf5334f
Create Date: 2026-01-27 09:55:37.967345

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10fe2495f036"
down_revision: Union[str, Sequence[str], None] = "e4332cf5334f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["note_id"], ["notes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("note_id", "chunk_index", name="uq_note_chunks_note_id_chunk_index"),
    )
    op.create_index(op.f("ix_note_chunks_id"), "note_chunks", ["id"], unique=False)
    op.create_index(op.f("ix_note_chunks_note_id"), "note_chunks", ["note_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_note_chunks_note_id"), table_name="note_chunks")
    op.drop_index(op.f("ix_note_chunks_id"), table_name="note_chunks")
    op.drop_table("note_chunks")
    # ### end Alembic commands ###
